/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as StaffEmployeesRouteImport } from './routes/staff/employees'
import { Route as StaffTablesIndexRouteImport } from './routes/staff/tables/index'
import { Route as StaffTablesTableIdRouteImport } from './routes/staff/tables/$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEmployeesRoute = StaffEmployeesRouteImport.update({
  id: '/staff/employees',
  path: '/staff/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTablesIndexRoute = StaffTablesIndexRouteImport.update({
  id: '/staff/tables/',
  path: '/staff/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTablesTableIdRoute = StaffTablesTableIdRouteImport.update({
  id: '/staff/tables/$tableId',
  path: '/staff/tables/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/staff/employees': typeof StaffEmployeesRoute
  '/staff/tables/$tableId': typeof StaffTablesTableIdRoute
  '/staff/tables/': typeof StaffTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/staff/employees': typeof StaffEmployeesRoute
  '/staff/tables/$tableId': typeof StaffTablesTableIdRoute
  '/staff/tables': typeof StaffTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/staff/employees': typeof StaffEmployeesRoute
  '/staff/tables/$tableId': typeof StaffTablesTableIdRoute
  '/staff/tables/': typeof StaffTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/restaurants'
    | '/staff/employees'
    | '/staff/tables/$tableId'
    | '/staff/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/restaurants'
    | '/staff/employees'
    | '/staff/tables/$tableId'
    | '/staff/tables'
  id:
    | '__root__'
    | '/'
    | '/restaurants'
    | '/staff/employees'
    | '/staff/tables/$tableId'
    | '/staff/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsRoute: typeof RestaurantsRoute
  StaffEmployeesRoute: typeof StaffEmployeesRoute
  StaffTablesTableIdRoute: typeof StaffTablesTableIdRoute
  StaffTablesIndexRoute: typeof StaffTablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/employees': {
      id: '/staff/employees'
      path: '/staff/employees'
      fullPath: '/staff/employees'
      preLoaderRoute: typeof StaffEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/tables/': {
      id: '/staff/tables/'
      path: '/staff/tables'
      fullPath: '/staff/tables/'
      preLoaderRoute: typeof StaffTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/tables/$tableId': {
      id: '/staff/tables/$tableId'
      path: '/staff/tables/$tableId'
      fullPath: '/staff/tables/$tableId'
      preLoaderRoute: typeof StaffTablesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsRoute: RestaurantsRoute,
  StaffEmployeesRoute: StaffEmployeesRoute,
  StaffTablesTableIdRoute: StaffTablesTableIdRoute,
  StaffTablesIndexRoute: StaffTablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
